language: node_js

node_js:
  - node

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - node --version
  - npm --version
  - npm install -g @angular/cli

script:
  - npm run lint || travis_terminate 1;
  - npm run test || travis_terminate 1;
  - npm run e2e || travis_terminate 1;
  - npm run build || travis_terminate 1;
